import { ServerData } from "@/app/(tabs)/Server";

 export const servers: ServerData[] = [
    {
      id: 'us-1',
      country: 'United States',
      flag: '🇺🇸',
      city: 'New York',
      locations: 15,
      ping: 165,
      status: 'recommended',
    },
    {
      id: 'uk-1',
      country: 'United Kingdom',
      flag: '🇬🇧',
      city: 'London',
      locations: 11,
      ping: 543,
      status: 'available',
    },
    {
      id: 'de-1',
      country: 'Germany',
      flag: '🇩🇪',
      city: 'Berlin',
      locations: 44,
      ping: 543,
      status: 'available',
    },
    {
      id: 'au-1',
      country: 'Australia',
      flag: '🇦🇺',
      city: 'Sydney',
      locations: 46,
      ping: 543,
      status: 'available',
    },
    {
      id: 'en-1',
      country: 'England',
      flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
      city: 'Manchester',
      locations: 40,
      ping: 543,
      status: 'available',
    },
    {
      id: 'ca-1',
      country: 'Canada',
      flag: '🇨🇦',
      city: 'Toronto',
      locations: 20,
      ping: 85,
      status: 'recommended',
    },
    {
      id: 'fr-1',
      country: 'France',
      flag: '🇫🇷',
      city: 'Paris',
      locations: 30,
      ping: 120,
      status: 'available',
    },
    {
      id: 'jp-1',
      country: 'Japan',
      flag: '🇯🇵',
      city: 'Tokyo',
      locations: 25,
      ping: 150,
      status: 'available',
    },
  ];